[package]
name = "corrent"
version = "0.1.0"
edition = "2024"

[dependencies]
bencoding = "0.1.3"
hex-literal = "1.0.0"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
sha1 = "0.10.6"
